function T = leg_force_new(F,Tp,phi1,phi4)
%LEG_FORCE_NEW
%    T = LEG_FORCE_NEW(F,Tp,PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2024-11-20 10:17:50

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = imag(t2);
t7 = real(t2);
t8 = imag(t4);
t9 = real(t4);
t10 = -t2;
t11 = t2.*1.8e+1;
t12 = t3.*1.8e+1;
t13 = -t5;
t19 = t2.*(3.0./2.0e+1);
t21 = t4.*1.5e-1i;
t24 = t4.*(8.1e+1./1.0e+3);
t25 = t5.*(8.1e+1./1.0e+3);
t14 = -t11;
t15 = t6.*1.0e+1;
t16 = t7.*1.0e+1;
t17 = t8.*1.0e+1;
t18 = t9.*1.0e+1;
t20 = t4+t13;
t22 = t3+t10+1.0;
t27 = -t24;
t23 = t20.^2;
t26 = t22.^2;
t28 = t23.*5.0;
t29 = t26.*5.0;
t30 = t23.*3.24e+2;
t31 = t26.*3.24e+2;
t32 = t23+t26;
t33 = t32.^2;
t36 = t12+t14+t28+t29+1.8e+1;
t34 = t33.*2.5e+1;
t37 = 1.0./t36;
t35 = -t34;
t38 = t30+t31+t35;
t39 = sqrt(t38);
t40 = t39.*4.5e-3;
t41 = t25+t27+t40;
t42 = t37.*t41.*2.222222222222222e+2;
t43 = atan(t42);
t44 = t43.*2.0;
t45 = cos(t44);
t46 = sin(t44);
t47 = imag(t45);
t48 = real(t45);
t49 = imag(t46);
t50 = real(t46);
t55 = t45.*(2.7e+1./1.0e+2);
t56 = t46.*2.7e-1i;
t51 = t47.*1.8e+1;
t52 = t48.*1.8e+1;
t53 = t49.*1.8e+1;
t54 = t50.*1.8e+1;
t57 = t19+t21+t55+t56-3.0./4.0e+1;
t58 = abs(t57);
t59 = 1.0./t58;
T = [F.*t59.*(t15+t16-t17+t18+t51+t52-t53+t54-5.0).*(3.0./2.0e+2)-Tp.*t59.*1.0./sqrt((t4.*5.0+t46.*9.0).^2.*4.0+(t2.*1.0e+1+t45.*1.8e+1-5.0).^2).*(t15-t16+t17+t18+t51-t52+t53+t54+5.0);0.0];
end
