function phi3_explicit = phi3_calculation(l1,l2,l3,l4,phi1,phi4)
%PHI3_CALCULATION
%    PHI3_EXPLICIT = PHI3_CALCULATION(L1,L2,L3,L4,PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2024-11-22 09:53:17

t2 = l1.^2;
t3 = l2.^2;
t4 = l3.^2;
t5 = l4.^2;
t6 = l1.*l4.*2.0;
t7 = l2.*l3.*2.0;
t9 = phi1./2.0;
t10 = phi4./2.0;
t8 = -t6;
t11 = -t3;
t12 = tan(t9);
t13 = tan(t10);
t14 = t12.^2;
t15 = t13.^2;
t30 = l1.*l4.*t12.*t13.*8.0;
t16 = t2.*t14;
t17 = t3.*t14;
t18 = t4.*t14;
t19 = t2.*t15;
t20 = t5.*t14;
t21 = t3.*t15;
t22 = t4.*t15;
t23 = t5.*t15;
t24 = t6.*t14;
t25 = t7.*t14;
t26 = t6.*t15;
t27 = t7.*t15;
t28 = t11.*t14;
t29 = t11.*t15;
t31 = -t30;
t38 = l1.*l4.*t14.*t15.*-2.0;
t32 = t15.*t16;
t33 = t15.*t17;
t34 = t15.*t18;
t35 = t15.*t20;
t36 = t15.*t24;
t37 = t15.*t25;
t39 = t15.*t28;
et1 = atan((sqrt((-t2+t3+t4-t5+t6+t7-t16+t17+t18-t19-t20+t21+t22-t23+t25+t27+t30-t32+t33+t34-t35+t36+t37-l1.*l4.*t14.*2.0-l1.*l4.*t15.*2.0).*(t2-t4+t5+t7+t8+t11+t16-t18+t19+t20-t22+t23+t24+t25+t26+t27+t28+t29+t31+t32-t34+t35+t37+t38+t39))-l1.*l3.*t12.*4.0+l3.*l4.*t13.*4.0-l1.*l3.*t12.*t15.*4.0+l3.*l4.*t13.*t14.*4.0)./(t2+t4+t5+t8+t11+t16+t18+t19+t20+t22+t23+t24+t26+t28+t29+t31+t32+t34+t35+t38+t39+l1.*l3.*2.0-l3.*l4.*2.0-l1.*l3.*t14.*2.0+l1.*l3.*t15.*2.0-l3.*l4.*t14.*2.0+l3.*l4.*t15.*2.0-l1.*l3.*t14.*t15.*2.0+l3.*l4.*t14.*t15.*2.0));
et2 = -2.0;
phi3_explicit = et1.*et2;
end
